### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AnthonyAUTSE2016**
[Evidence of Development process.docx](https://github.com/briardods/Mutiny/files/282748/Evidence.of.Development.process.docx)

### CODE REVIEW

**Comment by AnthonyAUTSE2016** [comment]
[Manage Change.docx](https://github.com/briardods/Mutiny/files/282860/Manage.Change.docx)

I think i might have included lots of unimportant ideas?

**Comment by AnthonyAUTSE2016** [comment]
[Individual Retrospective.docx](https://github.com/briardods/Mutiny/files/282923/Individual.Retrospective.docx)

**Comment by AnthonyAUTSE2016** [comment]
[Collaboration and Communication.docx](https://github.com/briardods/Mutiny/files/283025/Collaboration.and.Communication.docx)
sorry if ive spammed your G-unit mail. Hopefully the citation are done properly. Ff there is anything i need to fix please hit me up.

**Comment by briardods** [comment]
@AnthonyAUTSE2016 your change management doc is a good start. You need to do a bit of editing though. This document should act as a guide to the start-up. Iit would be a good idea to clearly explain how the start-up should manage change (with some of the supporting information you already have), rather than give them options.

**Comment by AnthonyAUTSE2016** [comment]
Ill modify that asap (send you tonight. working on status report for RnD
atm). Sorry I cant make the deadline we mentioned yesterday. And have you
looked at my other practice guideline for collaboration and communication?

**Comment by AnthonyAUTSE2016** [comment]
[Collaboration and Communication V.2.docx](https://github.com/briardods/Mutiny/files/284528/Collaboration.and.Communication.V.2.docx)


[Manage Change V1.5.docx](https://github.com/briardods/Mutiny/files/284529/Manage.Change.V1.5.docx)

So for the Change management. I hope it comes off more as a guide than a information section

**Pull request merged**
